version: "3.8"

# Define common healthcheck defaults using YAML anchors
x-health-defaults: &health-defaults
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 10s

# Define common environment variables for Temporal using Scylla as backend
x-temporal-backend-scylla: &temporal-backend-scylla
  CASSANDRA_PORT: 9042
  CASSANDRA_SEEDS: scylla

services:
  scylla:
    image: scylladb/scylla:6.2
    container_name: scylla
    ports:
      - "9042:9042"       # CQL port for client connections
      - "10000:10000"     # (Optional) additional port (e.g., for internals)
    volumes:
      - scylla-data:/var/lib/scylla
    healthcheck:
      <<: *health-defaults
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE keyspaces;'"]

  temporal:
    container_name: temporal
    depends_on:
      scylla:
        condition: service_healthy
    environment:
      <<: *temporal-backend-scylla
    image: temporalio/auto-setup:1.22
    ports:
      - "7233:7233"  # Temporal gRPC frontend port

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - TEMPORAL_CLI_SHOW_STACKS=1
    image: temporalio/admin-tools:1.22
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
      - TEMPORAL_CSRF_COOKIE_INSECURE=true
    image: temporalio/ui:2.21.3
    ports:
      - "8085:8080"  # Access Temporal UI via http://localhost:8085

volumes:
  scylla-data:
