version: "3.5"

# Define common healthcheck defaults using YAML anchors
x-health-defaults: &health-defaults
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 10s

# Define common environment variables for Temporal using Scylla as backend
x-temporal-backend-scylla: &temporal-backend-scylla
  CASSANDRA_PORT: 9042
  CASSANDRA_SEEDS: scylladb

services:
  scylladb:
    container_name: temporal-scylladb
    image: scylladb/scylla:6.2
    networks:
      - temporal-network
    ports:
      - "9042:9042"
    volumes:
      - scylla-data:/var/lib/scylla

  elasticsearch:
    container_name: temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:7.16.2
    networks:
      - temporal-network
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data

  temporal:
    container_name: temporal
    depends_on:
      - scylladb
      - elasticsearch
    environment:
      - DB=cassandra
      - CASSANDRA_SEEDS=scylladb
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:1.26.2
    networks:
      - temporal-network
    ports:
      - "7233:7233"

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.26.2
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.31.2
    networks:
      - temporal-network
    ports:
      - "8080:8080"

  server:
    container_name: temporal-workflow-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
    networks:
      - temporal-network
    ports:
      - "8081:8081"
    depends_on:
      - temporal
    healthcheck:
      <<: *health-defaults
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8081/healthz"]

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  scylla-data:
  elasticsearch-data:
